### ISSUE TITLE
As a user, I want to post questions so that I can receive insightful answers from other members of the community.

### ISSUE THREAD

**Issue by Josephj9720** [kaosalrim/SOEN341_Team_Project#16]
#5 Epic: Ask and Answer Questions

Priority: High
Story points: 20
High risk: New technology learning for UI. Model/Controller design.

Tasks:

- [x] #42
- [x] #43
- [x] #44
- [x] #45
- [x] #46
- [x] #47
- [x] #75

**Comment by kaosalrim** [comment]
all tasks done. closed
