### ISSUE TITLE
As a user, I want to post answers to open questions so that I can share my knowledge and experience with the community.

### ISSUE THREAD

**Issue by isleepontree10** [kaosalrim/SOEN341_Team_Project#19]
#5 Epic: Ask and Answer Questions

Priority: High
Story points: 15
Medium risk: The answer component is similar to the question component, requires integration into the question component. Controller/Model design required.

Tasks:

- [x] #48
- [x] #49
- [x] #50
- [x] #51
- [x] #52
- [x] #53

**Comment by isleepontree10** [comment]
description:
	-this user story is for the ability for a user to answer and post the answer to a posted question.

features:
	-each answer to the question requires id
	-each answer need id from account it was posted from 
	-each answer needs their own id to not erase or overwrite other questions
	-need to be able to see the top rated answer to the question at the top
	-ability to comment the answers from other users
	-id on the comments to the questions from users
	-should be able to post images and write text in answers

story points:8/10 	(work involved )       	->there is a significant amount of work involved in developing this feature
risk:9/10 		        (knowledge of task)	->high lack of knowledge in to this task
priority:10/10		(completion order)  	->crucial to the project

**Comment by kaosalrim** [comment]
all tasks completed
