### ISSUE TITLE
As a user, I want to have an account in order to track my posted questions and answers. 

### ISSUE THREAD

**Issue by gul2223** [kaosalrim/SOEN341_Team_Project#22]
#5 Epic: Ask/Answer Questions
Priority: Critical
Story points: 25
High risk: A user account is critical to the functionality of the website. Requires UI design for registration and authentications. The user controller and model need to be designed. Future enhancement is to allow third-party login, and adding "Remember me" option

Tasks:
- [x] #32
- [x] #33
- [x] #34
- [x] #35
- [ ] #36
- [ ] #37
- [x] #38
- [x] #39
- [x] #40
- [x] #41
- [x] #72

**Comment by kaosalrim** [comment]
Priority: Critical
Story points: 25
High risk: A user account is critical to the functionality of the website. Requires UI design for registration and authentications. The user controller and model need to be designed. Future enhancement is to allow third-party login, and adding "Remember me" option

Tasks:
- [ ] Create registration form
- [ ] Create login form
- [ ] Create User controller
- [ ] Create User model
- [ ] Create Google sign in
- [ ] Create Facebook sign in
- [ ] Add "Remember me option"

**Comment by kaosalrim** [comment]
All done exept Google sign in and Facebook sign. Those two will be considered as enchancement.
