### ISSUE TITLE
As a user, I want to have a question and answer environment in order to share experience and knowledge among community.

### ISSUE THREAD

**Issue by HAOlleik** [kaosalrim/SOEN341_Team_Project#5]
Story points: 50
Priority: Critical
High risk: UI development requires learning new technologies that none of the team members have experience with

Stories:
- User requires a default landing page with the following functionalities:
           - List of recent questions
           - Navigation menu
           - Side menu
           - Login/Register buttons
           - Post a new question button
- User needs the ability to post/answer questions

**Comment by isleepontree10** [comment]
#19

**Comment by isleepontree10** [comment]
As a developer, I want to answer questions so that other developers receive help and learn from me. #19

**Comment by kaosalrim** [comment]
Story points: 50
Priority: Critical
High risk: UI development requires learning new technologies that none of the team members have experience with

**Comment by kaosalrim** [comment]
all tasks done. closed
