### ISSUE TITLE
Epic User Story: Upvote/Downvote the answers

### ISSUE THREAD

**Issue by kamarkibbi** [kaosalrim/SOEN341_Team_Project#8]
As a user, I want to have an option to rank the answers in order to promote the best ones.

Priority: Medium
Story points: 25
Low risk: Most of the design is done in #5. Only new functionality is added, functionality update to views/controleers/models.

User stories

- Upvote answer
- Downvote answer 
- Display highest rank answer first

**Comment by kaosalrim** [comment]
all tasks done. closed
